@startuml
skin rose
left to right direction

package UI {
	usecase SeeRanking
	usecase PauseGame
}

package Settings {
	usecase SetBoardSize
	usecase SetLanguage
	usecase SetNumPlayers
}

package Gameplay {
	usecase ThinkMove
	usecase MakeMove
	usecase PutPiece
	usecase DrawPiece
	usecase SkipTurn
}

package Repository {
	usecase SaveGame
	usecase LoadGame
}

actor Player
actor CPU

SeeRanking -- Player
PauseGame -- Player

SetBoardSize -- Player
SetLanguage -- Player
SetNumPlayers -- Player

Player -- MakeMove
Player -- PutPiece
Player -- SkipTurn
Player -- DrawPiece

PutPiece -- CPU
MakeMove -- CPU
SkipTurn -- CPU
DrawPiece -- CPU
ThinkMove -- CPU

Player -- SaveGame
Player -- LoadGame

@enduml